# Generated by Django 5.2 on 2025-04-13 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newspaper", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Advertisement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="advertisements/%Y/%m/%d")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["name"],
                "verbose_name": "categories",
                "verbose_name_plural": "Categories",
            },
        ),
    ]
