# Generated by Django 5.2 on 2025-04-16 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newspaper", "0002_advertisement_alter_category_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="icon",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
