# Generated by Django 5.2 on 2025-04-17 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newspaper", "0004_category_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("message", models.TextField()),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("subject", models.CharField(max_length=200)),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
